### ISSUE TITLE
Error when re-partitionning a .h5 file obtained from the panmodule subcommand

### ISSUE THREAD

**Issue by ggautreau** [labgem/PPanGGOLiN#102]
```
ppanggolin partition -p ppanggolin/pangenome.h5 -b 10 –f

2023-01-17 15:09:55 main.py:l214 INFO   Command: XXX/miniconda3/bin/ppanggolin partition -p ppanggolin/pangenome.h5 -b 10 -f
2023-01-17 15:09:55 main.py:l215 INFO   PPanGGOLiN version: 1.2.74
2023-01-17 15:09:55 readBinaries.py:l39 INFO    Getting the current pangenome's status
2023-01-17 15:09:55 writeBinaries.py:l627 INFO  Erasing the formerly computed modules...
Traceback (most recent call last):
  File "XXX/miniconda3/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "XXX/miniconda3/lib/python3.7/site-packages/ppanggolin/main.py", line 223, in main
    ppanggolin.nem.partition.launch(args)
  File "XXX/miniconda3/lib/python3.7/site-packages/ppanggolin/nem/partition.py", line 501, in launch
    args.cpu, args.seed, args.keep_tmp_files, disable_bar=args.disable_prog_bar)
  File "XXX/miniconda3/lib/python3.7/site-packages/ppanggolin/nem/partition.py", line 366, in partition
    checkPangenomeFormerPartition(pangenome, force)
  File "XXX/miniconda3/lib/python3.7/site-packages/ppanggolin/nem/partition.py", line 353, in checkPangenomeFormerPartition
    ErasePangenome(pangenome, partition=True)
  File "XXX/miniconda3/lib/python3.7/site-packages/ppanggolin/formats/writeBinaries.py", line 634, in ErasePangenome
    h5f.del_node_attr(infoGroup, "StatOfFamiliesInModules")
  File "XXX/miniconda3/lib/python3.7/site-packages/tables/file.py", line 1871, in del_node_attr
    obj._f_delattr(attrname)
  File "XXX/miniconda3/lib/python3.7/site-packages/tables/node.py", line 907, in _f_delattr
    delattr(self._v_attrs, name)
  File "XXX/miniconda3/lib/python3.7/site-packages/tables/attributeset.py", line 539, in __delattr__
    % (name, self._v__nodepath))
AttributeError: Attribute ('StatOfFamiliesInModules') does not exist in node '/info'
Closing remaining open files:ppanggolin/pangenome.h5...done
```

**Comment by axbazin** [comment]
This bug was fixed in commit df00526 , installing a new version from master should work nicely.

The problem came from the "metrics" command which optionnaly writes some additionnal information in the .hdf5 file, but those metrics were always being deleted when "erasing" the pangenome bits corresponding to modules. So if metrics was never called, it crashed.
