### ISSUE TITLE
Spot Plot Error

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#109]
I am using the latest released version of ppanggolin and unable to produce spot plots due to the following error:

Traceback (most recent call last):
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/bin/ppanggolin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/ppanggolin/main.py", line 163, in main
    ppanggolin.figures.launch(args)
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/ppanggolin/figures/drawing.py", line 34, in launch
    draw_spots(pangenome=pangenome, output=args.output, spot_list=args.spots, disable_bar=args.disable_prog_bar)
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/ppanggolin/figures/draw_spot.py", line 658, in draw_spots
    draw_selected_spots(selected_spots, pangenome, output,
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/ppanggolin/figures/draw_spot.py", line 621, in draw_selected_spots
    draw_curr_spot(uniq_gene_lists, ordered_counts, fam2mod, famcolors, fname)
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/ppanggolin/figures/draw_spot.py", line 521, in draw_curr_spot
    fig = figure(title="spot graphic", plot_width=1600, plot_height=600,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/bokeh/plotting/_figure.py", line 190, in __init__
    self._raise_attribute_error_with_matches(name, names | opts.properties())
  File "/Users/XXX/opt/anaconda3/envs/ppgg-dev/lib/python3.11/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

**Comment by axbazin** [comment]
Hi,

This is a problem with the bokeh dependency, it's likely version 3.X.X while it should be version 2.X.X . If you use the env from bioconda it should install the proper version of bokeh.

Adelme

**Comment by ggautreau** [comment]
@seajane @axbazin May I close this issue?
