### ISSUE TITLE
Attribute error drawing plots

### ISSUE THREAD

**Issue by cizydorczyk** [labgem/PPanGGOLiN#121]
I get an error when running ppanggolin (v1.2.105) using fasta files:

```
2023-06-21 22:26:52 draw_spot.py:l565 INFO	Ordering genes among regions, and drawing spots...
  0%|                                                                                               | 0/25 [00:00<?, ?spot/s]
Traceback (most recent call last):
  File "/home/conrad/anaconda3/envs/ppanggolin-env/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/home/conrad/anaconda3/envs/ppanggolin-env/lib/python3.10/site-packages/ppanggolin/main.py", line 181, in main
    ppanggolin.workflow.panRGP.launch(args)
  File "/home/conrad/anaconda3/envs/ppanggolin-env/lib/python3.10/site-packages/ppanggolin/workflow/panRGP.py", line 100, in launch
    draw_spots(pangenome=pangenome, output=args.output, spot_list='all', disable_bar=args.disable_prog_bar)
  File "/home/conrad/anaconda3/envs/ppanggolin-env/lib/python3.10/site-packages/ppanggolin/figures/draw_spot.py", line 658, in draw_spots
    draw_selected_spots(selected_spots, pangenome, output,
  File "/home/conrad/anaconda3/envs/ppanggolin-env/lib/python3.10/site-packages/ppanggolin/figures/draw_spot.py", line 621, in draw_selected_spots
    draw_curr_spot(uniq_gene_lists, ordered_counts, fam2mod, famcolors, fname)
  File "/home/conrad/anaconda3/envs/ppanggolin-env/lib/python3.10/site-packages/ppanggolin/figures/draw_spot.py", line 521, in draw_curr_spot
    fig = figure(title="spot graphic", plot_width=1600, plot_height=600,
  File "/home/conrad/.local/lib/python3.10/site-packages/bokeh/plotting/_figure.py", line 190, in __init__
    self._raise_attribute_error_with_matches(name, names | opts.properties())
  File "/home/conrad/.local/lib/python3.10/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width
```

Any ideas what might be the issue?

Here is the conda environment I am running:

```
# packages in environment at /home/conrad/anaconda3/envs/ppanggolin-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
blosc                     1.21.4               h0f2a231_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
c-blosc2                  2.9.2                hb4ffafa_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorlover                0.3.0                      py_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gawk                      5.1.0                h7f98852_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py310h3ec546c_1    conda-forge
hdf5                      1.14.0          nompi_hb72d44e_103    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
infernal                  1.1.4           pl5321h031d066_4    bioconda
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mafft                     7.520                h031d066_2    bioconda
markupsafe                2.1.3           py310h2372a71_0    conda-forge
mmseqs2                   13.45111        pl5321hf1761c0_2    bioconda
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.4           py310h690d005_100    conda-forge
numpy                     1.25.0          py310ha4c1d20_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h9b08913_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.5.0           py310h582fbeb_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
platformdirs              3.6.0              pyhd8ed1ab_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
ppanggolin                1.2.105         py310h4b81fae_1    bioconda
prodigal                  2.6.3                h031d066_6    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.8.0           py310hde6a235_1    conda-forge
python                    3.10.11         he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scipy                     1.10.1          py310ha4c1d20_3    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.3.2           py310h2372a71_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zlib-ng                   2.0.7                h0b41bf4_0    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by cizydorczyk** [comment]
I don't really care about the plots but more so the RGPs identified. 

Can output of the panrgp pipeline be produced without plotting?
