### ISSUE TITLE
Exception: The gene family has not beed associated to a partition

### ISSUE THREAD

**Issue by JamieAlfieri** [labgem/PPanGGOLiN#148]
I'm trying to make an MSA of 51 fasta files. These fasta files are CDS from isolates.

I ran `ppanggolin workflow --fasta ORGANISMS_FASTA_LIST.txt --cpu 20`, but I get this error:

`Traceback (most recent call last):
File "/homepath/mambaforge/pango/bin/ppanggolin", line 10, in
sys.exit(main())
File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/main.py", line 159, in main
ppanggolin.workflow.workflow.launch(args)
File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/workflow/workflow.py", line 64, in launch
write_pangenome(pangenome, filename, args.force, disable_bar=args.disable_prog_bar)
File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/formats/writeBinaries.py", line 953, in write_pangenome
write_info(pangenome, h5f)
File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/formats/writeBinaries.py", line 643, in write_info
named_part_counter[fam.named_partition] += 1
File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/geneFamily.py", line 65, in named_partition
raise Exception("The gene family has not beed associated to a partition")
Exception: The gene family has not beed associated to a partition
/homepath/mambaforge/pango/lib/python3.10/site-packages/tables/file.py:113: UnclosedFileWarning:

Closing remaining open file: ppanggolin_output_DATE2023-12-07_HOUR14.03.12_PID222227/pangenome.h5`

Consequently, I can't run `ppanggolin msa -p pangenome.h5 --phylo --cpu 20 --output msaoutput --source dna`, and get this error:

`2023-12-07 14:19:08 writeMSA.py:l304 INFO	Doing MSA for core families...
Traceback (most recent call last):
  File "/homepath/mambaforge/pango/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/main.py", line 169, in main
    ppanggolin.formats.writeMSA.launch(args)
  File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/formats/writeMSA.py", line 338, in launch
    writeMSAFiles(pangenome, args.output, cpu=args.cpu, partition=args.partition, tmpdir=args.tmpdir,
  File "/homepath/mambaforge/pango/lib/python3.10/site-packages/ppanggolin/formats/writeMSA.py", line 308, in writeMSAFiles
    if 'translation_table' in pangenome.parameters["cluster"]:
KeyError: 'cluster'`

My ORGANISMS_FASTA_LIST.txt file is correctly formatted, and I can't figure out the reason this code isn't running, as I've successfully used it before with MAG data.

Thank you

**Comment by axbazin** [comment]
Hi,

You said that you're ORGANISMS_FASTA_LIST.txt is made of CDS ? I have no idea how it manages to get to this point showed in the log, but this ORGANISMS_FASTA_LIST.txt is only useful when using fasta files that correspond to genome(-like) sequences. It's really not expected (nor meant) to have CDS sequences given to the workflow subcommand.

If you already have your 51 CDS sequences in a single (or multiple) fasta files, you can probably use mafft directly on that fasta file to get your MSA, Mafft is the tool that PPanGGOLiN uses to compute MSA. 

Alternatively, you can build the pangenome of your isolates, by providing the genome sequences of the isolates, or their annotations to the PPanGGOLiN `workflow` command. Then you should be able to used the `ppanggolin msa` command like you wanted to originally. But the 'mafft' approach is likely much simpler and much faster for what you describe.

Adelme

**Comment by JamieAlfieri** [comment]
Ah, I was afraid that was the issue.

We are updating our pipelines to handle MAGs, so we now use ppanggolin (which is great for its intended purpose). I was trying to compare results from our old pipeline (of which we only have CDS sequences as input data), by running ppanggolin on that. Thank you for your help.
