### ISSUE TITLE
Error since update to 2.0

### ISSUE THREAD

**Issue by SamVaGo** [labgem/PPanGGOLiN#172]
Dear

I updated ppanggolin to its newest version (2.0.1) today. I wanted to re-analyse my genomes but I allways get a clustering error.

This is what happens:

ppanggolin all --anno input_gff.csv --output ppanggolin3 --cpu 12
2024-01-23 16:52:35 utils.py:l167 INFO	Command: /home/britto/anaconda3/envs/ppanggolin/bin/ppanggolin all --anno input_gff.csv --output ppanggolin3 --cpu 12
2024-01-23 16:52:35 utils.py:l168 INFO	PPanGGOLiN version: 2.0.1
2024-01-23 16:52:35 utils.py:l721 INFO	9 parameters have a non-default value.
2024-01-23 16:52:35 annotate.py:l497 INFO	Reading input_gff.csv the list of genome files ...
100%|███████████████████████████████████████████████████| 453/453 [00:35<00:00, 12.67file/s]
2024-01-23 16:53:11 annotate.py:l532 INFO	gene identifiers used in the provided annotation files were not unique, PPanGGOLiN will use self-generated identifiers.
2024-01-23 16:53:11 writeBinaries.py:l708 INFO	Writing genome annotations...
100%|█████████████████████████████████████████████| 453/453 [00:00<00:00, 652255.31genome/s]
100%|████████████████████████████████████████| 42906/42906 [00:00<00:00, 520949.05contigs/s]
100%|███████████████████████████████████████| 2173846/2173846 [00:12<00:00, 173720.35gene/s]
100%|███████████████████████████████████| 1633309/1633309 [00:03<00:00, 524513.80genedata/s]
100%|████████████████████████████████████████████| 41968/41968 [00:00<00:00, 218951.02RNA/s]
100%|███████████████████████████████████████| 27210/27210 [00:00<00:00, 606532.70genedata/s]
2024-01-23 16:53:32 writeBinaries.py:l719 INFO	writing the protein coding gene dna sequences in pangenome...
100%|███████████████████████████████████████| 2173846/2173846 [00:05<00:00, 423614.23gene/s]
2024-01-23 16:53:52 writeBinaries.py:l764 INFO	Done writing the pangenome. It is in file : ppanggolin3/pangenome.h5
2024-01-23 16:53:52 writeSequences.py:l38 INFO	Writing all CDS sequences in /tmp/clustering_tmpdir_2024-01-23_16.53.52/nucleotid_sequences
2173846gene [00:05, 432487.06gene/s]
2024-01-23 16:53:57 cluster.py:l315 INFO	Clustering all of the genes sequences...
2024-01-23 16:53:57 cluster.py:l90 INFO	Creating sequence database...
2024-01-23 16:54:13 cluster.py:l97 INFO	Clustering sequences...
2024-01-23 16:54:38 cluster.py:l103 INFO	Extracting cluster representatives...
2024-01-23 16:54:39 cluster.py:l112 INFO	Writing gene to family informations
2024-01-23 16:54:39 cluster.py:l323 INFO	Associating fragments to their original gene family...
2024-01-23 16:54:40 cluster.py:l156 INFO	Aligning cluster representatives...
2024-01-23 16:55:01 cluster.py:l162 INFO	Extracting alignments...
2024-01-23 16:55:03 cluster.py:l202 INFO	Starting with 31746 families
2024-01-23 16:55:03 cluster.py:l236 INFO	Ending with 23447 gene families
2024-01-23 16:55:04 cluster.py:l247 INFO	Adding protein sequences to the gene families
2024-01-23 16:55:04 cluster.py:l262 INFO	Adding 1942374 genes to the gene families
Traceback (most recent call last):
  File "/home/britto/anaconda3/envs/ppanggolin/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/home/britto/anaconda3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/main.py", line 219, in main
    ppanggolin.workflow.all.launch(args)
  File "/home/britto/anaconda3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 286, in launch
    launch_workflow(args, panrgp=True, panmodule=True)
  File "/home/britto/anaconda3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 79, in launch_workflow
    clustering(pangenome, tmpdir=args.tmpdir, cpu=args.cluster.cpu, force=args.force,
  File "/home/britto/anaconda3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/cluster/cluster.py", line 330, in clustering
    read_gene2fam(pangenome, genes2fam, disable_bar=disable_bar)
  File "/home/britto/anaconda3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/cluster/cluster.py", line 268, in read_gene2fam
    raise Exception("Something unexpected happened during clustering (have less genes clustered than genes "
Exception: Something unexpected happened during clustering (have less genes clustered than genes in the pangenome). A probable reason is that two genes in two different genomes have the same IDs; If you are sure that all of your genes have non identical IDs,  please post an issue at https://github.com/labgem/PPanGGOLiN/

What is going wrong here?

Many thanks in advance.

Best
Sam

**Comment by SamVaGo** [comment]
PS. multiple genomes are clonal clusters, but all GFF files are unique. Also, (if it matters) I could run the analysis on the previous version (with the exact same input file)

**Comment by axbazin** [comment]
Hi,
Thank you for reporting this !

This does not look easy to solve, do you think it would be possible to share your gffs files, or a subset of them that generates the same error, so that we can reproduce it and debug it more easily?

Best,
Adelme

**Comment by jpjarnoux** [comment]
Hi,
Could you also carry out a step-by-step analysis? This could solve the problem while we fix the bug.
Thanks

**Comment by SamVaGo** [comment]
> Hi, Thank you for reporting this !
> 
> This does not look easy to solve, do you think it would be possible to share your gffs files, or a subset of them that generates the same error, so that we can reproduce it and debug it more easily?
> 
> Best, Adelme

Yes, what would be the best way to send you these? I have tried subsetting, but the error occurs with every subset. I can send you a list of 5 GFF-files, which are actually all downloaded from NCBI and where the error is also generated.

**Comment by axbazin** [comment]
Hi,

It turned out that @jpjarnoux had a set of gff that were producing the same bug. Apparently it happens when some identifiers ('ID' field in gff files) are shared between gff files.

It turns out that when you go through the "step by step" approach as Jerome suggested, rather than the workflow, it works perfectly, because ppanggolin will use its internal identifiers which are always unique, in that case.

we're working on this and will notify you as soon as we have a working solution for the 'ppanggolin all' workflow in case of shared identifiers in the gff files !

Adelme

**Comment by SamVaGo** [comment]
Perfect, thank you! As suggested, the step-by-step approach works fine.
Many thanks!
