### ISSUE TITLE
invalid type <class 'str'> for column product

### ISSUE THREAD

**Issue by samuelmontgomery** [labgem/PPanGGOLiN#175]
Hi, similar to #95 i am having the below error

ppanggolin all --anno /home/ubuntu/scratch/analysis/pangenome/pan.tsv --cpu 16 --output /home/ubuntu/scratch/analysis/pangenome/output --tmp /home/ubuntu/scratch/tmp
2024-02-08 04:34:39 utils.py:l167 INFO  Command: /home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/bin/ppanggolin all --anno /home/ubuntu/scratch/analysis/pangenome/pan.tsv --cpu 16 --output /home/ubuntu/scratch/analysis/pangenome/output --tmp /home/ubuntu/scratch/tmp
2024-02-08 04:34:39 utils.py:l168 INFO  PPanGGOLiN version: 2.0.2
2024-02-08 04:34:39 utils.py:l721 INFO  10 parameters have a non-default value.
2024-02-08 04:34:39 annotate.py:l497 INFO       Reading pan.tsv the list of genome files ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:08<00:00, 11.55file/s]
2024-02-08 04:34:50 annotate.py:l529 INFO       gene identifiers used in the provided annotation files were unique, PPanGGOLiN will use them.
2024-02-08 04:34:50 writeBinaries.py:l708 INFO  Writing genome annotations...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 457156.94genome/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 192/192 [00:00<00:00, 305735.14contigs/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 620561/620561 [00:04<00:00, 140021.30gene/s]
  0%|▏                                                                                                                            | 646/620545 [00:00<00:01, 452114.20genedata/s]
Traceback (most recent call last):
  File "tables/tableextension.pyx", line 1676, in tables.tableextension.Row.__setitem__
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/main.py", line 219, in main
    ppanggolin.workflow.all.launch(args)
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 286, in launch
    launch_workflow(args, panrgp=True, panmodule=True)
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 61, in launch_workflow
    write_pangenome(pangenome, filename, args.force, disable_bar=args.disable_prog_bar)
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/formats/writeBinaries.py", line 710, in write_pangenome
    write_annotations(pangenome, h5f, disable_bar=disable_bar)
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/formats/writeAnnotations.py", line 342, in write_annotations
    write_genedata(pangenome, h5f, annotation, genedata2gene, disable_bar)
  File "/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/ppanggolin/formats/writeAnnotations.py", line 310, in write_genedata
    genedata_row["product"] = genedata.product
  File "tables/tableextension.pyx", line 1681, in tables.tableextension.Row.__setitem__
TypeError: invalid type (<class 'str'>) for column ``product``
/home/ubuntu/scratch/software/miniforge3/envs/ppanggolin/lib/python3.10/site-packages/tables/file.py:113: UnclosedFileWarning:

Closing remaining open file: /home/ubuntu/scratch/analysis/pangenome/output/pangenome.h5

They are bakta (v1.9.1) annotated genomes and the tsv has links to the gbff file

I tried using dos2unix on the tsv incase that was the issue but it is still happening

Can I try using the .faa output from bakta as input?

**Comment by axbazin** [comment]
Otherwise, you can probably find the problematic annotations using the solution David suggested here: https://github.com/labgem/PPanGGOLiN/issues/95#issuecomment-1259173679_

**Comment by samuelmontgomery** [comment]
I have run it - every single issue is COG2315
e.g.,
 `contig_1	Prodigal	CDS	5641880	5642236	.	-	0	ID=EMIMML_26880;Name=putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family;locus_tag=EMIMML_26880;product=putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family;Dbxref=COG:COG2315,COG:K,RefSeq:WP_003111913.1,SO:0001217,UniParc:UPI000045D240,UniRef:UniRef100_A0A0C6EJ52,UniRef:UniRef50_Q9I2B4,UniRef:UniRef90_Q9I2B4;gene=mmcQ`

Can't send through the files unfortunately

**Comment by axbazin** [comment]
Hi,

No problem for the files it's understandable.
I'm afraid, until we do find a proper workaround or the COG people fix this, your only simply way out of this one is to edit and remove the problematic characters. In your case they are the ```‘double-wing’``` characters, you can probably edit your files with an adequate `sed` command.

Adelme

**Comment by samuelmontgomery** [comment]
thanks - this did work
