### ISSUE TITLE
error while writing genome annotations

### ISSUE THREAD

**Issue by sulmanm1** [labgem/PPanGGOLiN#233]
I used the command  `ppanggolin panrgp --anno output.txt -c 40 -o ppanggolin_all ` on a txt mapping to bakta gff3 files and got the following error:

```
2024-06-03 12:01:44 utils.py:l168 INFO	Command: /home/biolinux/miniforge3/envs/pangenome/bin/ppanggolin panrgp --anno output.txt -c 40 -o ppanggolin_all -f
2024-06-03 12:01:44 utils.py:l169 INFO	PPanGGOLiN version: 2.0.5
2024-06-03 12:01:44 utils.py:l722 INFO	9 parameters have a non-default value.
2024-06-03 12:01:44 annotate.py:l503 INFO	Reading output.txt the list of genome files ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 164/164 [00:14<00:00, 11.60file/s]
2024-06-03 12:02:00 annotate.py:l535 INFO	gene identifiers used in the provided annotation files were unique, PPanGGOLiN will use them.
2024-06-03 12:02:00 writeBinaries.py:l709 INFO	Writing genome annotations...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 164/164 [00:00<00:00, 514869.65genome/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 6790/6790 [00:00<00:00, 376262.71contigs/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████| 746707/746707 [00:05<00:00, 133080.54gene/s]
  0%|                                                                                           | 920/720722 [00:00<00:02, 350414.06genedata/s]
Traceback (most recent call last):
  File "tables/tableextension.pyx", line 1676, in tables.tableextension.Row.__setitem__
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biolinux/miniforge3/envs/pangenome/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/main.py", line 213, in main
    ppanggolin.workflow.panRGP.launch(args)
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/workflow/panRGP.py", line 21, in launch
    launch_workflow(args, panrgp=True, panmodule=False)
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 61, in launch_workflow
    write_pangenome(pangenome, filename, args.force, disable_bar=args.disable_prog_bar)
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/formats/writeBinaries.py", line 711, in write_pangenome
    write_annotations(pangenome, h5f, disable_bar=disable_bar)
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/formats/writeAnnotations.py", line 342, in write_annotations
    write_genedata(pangenome, h5f, annotation, genedata2gene, disable_bar)
  File "/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/ppanggolin/formats/writeAnnotations.py", line 309, in write_genedata
    genedata_row["name"] = genedata.name
  File "tables/tableextension.pyx", line 1681, in tables.tableextension.Row.__setitem__
TypeError: invalid type (<class 'str'>) for column ``name``
/home/biolinux/miniforge3/envs/pangenome/lib/python3.10/site-packages/tables/file.py:113: UnclosedFileWarning:

Closing remaining open file: ppanggolin_all/pangenome.h5
```
Not sure what to do. I checked genedata_row["name"] and it is an empty byte, while the output of printing genedata_row is the following: /annotations/genedata.row (Row), pointing to row #0

**Comment by sulmanm1** [comment]
There was a non-ascii character in my gff3.
