### ISSUE TITLE
'ascii' codec 

### ISSUE THREAD

**Issue by yl030** [labgem/PPanGGOLiN#252]
Hello ppanggolin team,
I installed ppanggolin through manual and when I run % ppanggolin all --anno genomes.gff.list

100%|██████████| 2675/2675 [17:46<00:00,  2.51file/s]

  0%|          | 0/2675 [00:00<?, ?genome/s]
  0%|          | 0/2675 [00:00<?, ?genome/s]
Traceback (most recent call last):
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/main.py", line 222, in main
    ppanggolin.workflow.all.launch(args)
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 295, in launch
    launch_workflow(args, panrgp=True, panmodule=True)
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 62, in launch_workflow
    write_pangenome(pangenome, filename, args.force, disable_bar=args.disable_prog_bar)
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/formats/writeBinaries.py", line 709, in write_pangenome
    write_annotations(pangenome, h5f, disable_bar=disable_bar)
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/formats/writeAnnotations.py", line 390, in write_annotations
    write_organisms(pangenome, h5f, annotation, desc, disable_bar)
  File "/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/formats/writeAnnotations.py", line 74, in write_organisms
    organism_row["name"] = org.name
    ~~~~~~~~~~~~^^^^^^^^
  File "tables/tableextension.pyx", line 1673, in tables.tableextension.Row.__setitem__
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 0: ordinal not in range(128)
/gss1/App_os7/miniconda3/envs/ppanggolin/lib/python3.12/site-packages/tables/file.py:113: UnclosedFileWarning:

Closing remaining open file: ppanggolin_output_DATE2024-07-16_HOUR08.10.22_PID12964/pangenome.h5

**Comment by jpjarnoux** [comment]
Hi !

Could I know the source of the annotation files ?
It looks like there is an unknown field in your GFF. 
Related issue that could help #222 #232 #233

Also if none of that help you. Could you share your files or a sample that reproduce the error ?

Regards

**Comment by ShuyiF** [comment]
Hello Jérôme,

I have the same issue with my gff3 files generated from Bakta. And I used LC_ALL=C grep -n -P [$'\x80'-$'\xFF'] *.g*ff3 as you suggested in previous cases to identify the issue. Below were the issues I identified for one gff3 file.

s_GCA_001267655.1_ASM126765v1_genomic.gff3:3415:contig_45	Prodigal	CDS	505951	508116	.	-	0	ID=FPAJNN_16465;Name=ATPase/5???-3??? helicase helicase subunit RecD of the DNA repair enzyme RecBCD (exonuclease V);locus_tag=FPAJNN_16465;product=ATPase/5???-3??? helicase helicase subunit RecD of the DNA repair enzyme RecBCD (exonuclease V);Dbxref=COG:COG0507,COG:L,RefSeq:WP_053321089.1,SO:0001217,UniParc:UPI0006A746F1,UniRef:UniRef100_UPI0006A746F1,UniRef:UniRef50_A0A0Q0HAY0,UniRef:UniRef90_A0A2G4B1T5;gene=recD
s_GCA_001267965.1_ASM126796v1_genomic.gff3:1542:contig_16	Prodigal	CDS	206096	206449	.	-	0	ID=GADIJF_07445;Name=putative DNA-binding protein with ???double-wing??? structural motif%2C MmcQ/YjbR family;locus_tag=GADIJF_07445;product=putative DNA-binding protein with ???double-wing??? structural motif%2C MmcQ/YjbR family;Dbxref=COG:COG2315,COG:K,RefSeq:WP_043046211.1,SO:0001217,UniParc:UPI0005BA9E8B,UniRef:UniRef100_A0A7H5D073,UniRef:UniRef50_A0A0P7EVE8,UniRef:UniRef90_A0A227JFM2;gene=mmcQ

How could I use sed to solve this issue? I have 150 gff3 files that need to be fixed. Thank you for your help!!

**Comment by ShuyiF** [comment]
> Hello Jérôme,
> 
> I have the same issue with my gff3 files generated from Bakta. And I used LC_ALL=C grep -n -P [$'\x80'-$'\xFF'] _.g_ff3 as you suggested in previous cases to identify the issue. Below were the issues I identified for one gff3 file.
> 
> s_GCA_001267655.1_ASM126765v1_genomic.gff3:3415:contig_45 Prodigal CDS 505951 508116 . - 0 ID=FPAJNN_16465;Name=ATPase/5???-3??? helicase helicase subunit RecD of the DNA repair enzyme RecBCD (exonuclease V);locus_tag=FPAJNN_16465;product=ATPase/5???-3??? helicase helicase subunit RecD of the DNA repair enzyme RecBCD (exonuclease V);Dbxref=COG:COG0507,COG:L,RefSeq:WP_053321089.1,SO:0001217,UniParc:UPI0006A746F1,UniRef:UniRef100_UPI0006A746F1,UniRef:UniRef50_A0A0Q0HAY0,UniRef:UniRef90_A0A2G4B1T5;gene=recD s_GCA_001267965.1_ASM126796v1_genomic.gff3:1542:contig_16 Prodigal CDS 206096 206449 . - 0 ID=GADIJF_07445;Name=putative DNA-binding protein with ???double-wing??? structural motif%2C MmcQ/YjbR family;locus_tag=GADIJF_07445;product=putative DNA-binding protein with ???double-wing??? structural motif%2C MmcQ/YjbR family;Dbxref=COG:COG2315,COG:K,RefSeq:WP_043046211.1,SO:0001217,UniParc:UPI0005BA9E8B,UniRef:UniRef100_A0A7H5D073,UniRef:UniRef50_A0A0P7EVE8,UniRef:UniRef90_A0A227JFM2;gene=mmcQ
> 
> How could I use sed to solve this issue? I have 150 gff3 files that need to be fixed. Thank you for your help!!

I tried sed 's/[^\x00-\x7F]/'\''/g' input.gff3 > output.gff3 but the modified gff3 file becomes empty (0 kb). Do you have any suggestions? Thanks!!

**Comment by CedricMidoux** [comment]
I had the same problem with `\u2019` (`’` in `/product="ATPase/5’-3’ helicase helicase subunit RecD`)

**Comment by Tsingsjeen** [comment]
Does this issue solved? I also tried with output files, .gff3 and gbff from bakta, neither of them worked and same report errors, "UnicodeEncodeError: 'ascii' codec...". I then back to .fna files, it works, but the annotation became less clear.

**Comment by Tsingsjeen** [comment]
Sorry for the spam, now worked following the solution above!

**Comment by JeanMainguy** [comment]
With version [2.2.0](https://github.com/labgem/PPanGGOLiN/releases/tag/2.2.0), non-ASCII characters are now filtered out, which should prevent the error reported above.

Please don’t hesitate to reopen this issue or create a new one if the error reappears.

Thanks!

**Comment by marieleoz** [comment]
Hello,

Unfortunately I just got the same kind of issue while running PPanGGOLiN-v2.2.1 (see below). 
Please let me know if I should send the gff3 files.

Cheers,
Marie


2025-03-11 11:54:15 utils.py:l226 INFO	Command: /usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/bin/ppanggolin all --anno liste_annotation_bakta.txt --output ppanggolin_out --cpu 20 --kingdom bacteria --translation_table 11
2025-03-11 11:54:15 utils.py:l229 INFO	PPanGGOLiN version: 2.2.1
2025-03-11 11:54:15 utils.py:l963 INFO	10 parameters have a non-default value.
2025-03-11 11:54:15 annotate.py:l1518 INFO	Reading liste_annotation_bakta.txt the list of genome files ...
  0%|          | 0/4 [00:00<?, ?file/s]2025-03-11 11:54:15 annotate.py:l1086 WARNING	In genome 'D-I-1_Unicycler', the 'product' field of gene 'BMNOHK_23820' contains non-ASCII characters: 'putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family'. These characters cannot be stored in the HDF5 file and will be replaced by underscores.
2025-03-11 11:54:15 annotate.py:l1086 WARNING	In genome 'D-I-1_Shovill', the 'product' field of gene 'NOLIJE_23580' contains non-ASCII characters: 'putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family'. These characters cannot be stored in the HDF5 file and will be replaced by underscores.
2025-03-11 11:54:15 annotate.py:l1086 WARNING	In genome 'D-II-2_Shovill', the 'product' field of gene 'OJHEFF_24340' contains non-ASCII characters: 'putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family'. These characters cannot be stored in the HDF5 file and will be replaced by underscores.
2025-03-11 11:54:15 annotate.py:l1086 WARNING	In genome 'D-I-1_PacBio', the 'product' field of gene 'NHEBED_31450' contains non-ASCII characters: 'putative DNA-binding protein with ‘double-wing’ structural motif%2C MmcQ/YjbR family'. These characters cannot be stored in the HDF5 file and will be replaced by underscores.
100%|██████████| 4/4 [00:01<00:00,  2.37file/s]
2025-03-11 11:54:16 annotate.py:l1564 INFO	gene identifiers used in the provided annotation files were unique, PPanGGOLiN will use them.
2025-03-11 11:54:16 writeBinaries.py:l902 INFO	Writing genome annotations...
100%|██████████| 4/4 [00:00<00:00, 81840.08genome/s]
100%|██████████| 354/354 [00:00<00:00, 794426.76contigs/s]
100%|██████████| 25900/25900 [00:00<00:00, 315461.02gene/s]
 24%|██▍       | 6159/25899 [00:00<00:00, 819878.07genedata/s]
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/main.py", line 283, in main
    ppanggolin.workflow.all.launch(args)
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 464, in launch
    launch_workflow(args, panrgp=True, panmodule=True)
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 82, in launch_workflow
    write_pangenome(
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/formats/writeBinaries.py", line 904, in write_pangenome
    write_annotations(pangenome, h5f, disable_bar=disable_bar)
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/formats/writeAnnotations.py", line 514, in write_annotations
    write_genedata(pangenome, h5f, annotation, genedata2gene, disable_bar)
  File "/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/ppanggolin/formats/writeAnnotations.py", line 467, in write_genedata
    genedata_row["name"] = genedata.name
    ~~~~~~~~~~~~^^^^^^^^
  File "tables/tableextension.pyx", line 1733, in tables.tableextension.Row.__setitem__
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 34: ordinal not in range(128)
/usr/local/bioinfo/src/Miniforge/Miniforge3/envs/PPanGGOLiN-v2.2.1_env/lib/python3.12/site-packages/tables/file.py:130: UnclosedFileWarning:

Closing remaining open file: ppanggolin_out/pangenome.h5

**Comment by marieleoz** [comment]
Problem solved using iconv on my .gff3 files before submitting them to ppanggolin:
iconv -f UTF-8 -t ASCII//TRANSLIT input.gff3 -o output_ascii.gff3

**Comment by axbazin** [comment]
Hi,
Thank you for reporting. Indeed the bugfix provided by #291 only fixes this problem for the 'product' field of annotations, while it looks like in your case the non-ascii character was in a gene name if I'm not mistaken.

If one of your gene contains the ‘ character in the 'gene' or 'name' attribute, then it's probably because of this one.

Glad that you managed to solve things easily !
Adelme
