### ISSUE TITLE
Contig 1 already in genome

### ISSUE THREAD

**Issue by matiasWanntorp** [labgem/PPanGGOLiN#294]
Hello,

I am just using PPanGGOLiN for the first time and am encountering an error:

Traceback (most recent call last):
  File "/home/matwan/anaconda3/envs/ppanggolin/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/main.py", line 221, in main
    ppanggolin.workflow.all.launch(args)
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 295, in launch
    launch_workflow(args, panrgp=True, panmodule=True)
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/workflow/all.py", line 55, in launch_workflow
    read_annotations(pangenome, args.anno, pseudo=args.annotate.use_pseudo,
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/site-packages/ppanggolin/annotate/annotate.py", line 1079, in read_annotations
    org, has_dna_sequence = future.result()
                            ^^^^^^^^^^^^^^^
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/matwan/anaconda3/envs/ppanggolin/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: Reading the gff3 file '/seq/projects/novelLegio_Vlad/NovelLegionella/analysis/02_annotation/unicycler/gff_files/80869.gff' raised an error. 'Contig 1 already in genome 80869.gff

Here are the first few lines of the GFF3 file: 
##gff-version 3
#!gff-spec-version 1.21
#!processor NCBI annotwriter
##sequence-region  1 533939
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=445
1       Local   region  1       533939  .       +       .       ID=1:1..533939;Dbxref=taxon:445;Name=ANONYMOUS;gbkey=Src;genome=chromosome;mol_type=genomic DNA
1       .       gene    42      650     .       -       .       ID=gene-pgaptmp_000001;Name=lolA;gbkey=Gene;gene=lolA;gene_biotype=protein_coding;locus_tag=pgaptmp_000001
1       Protein Homology        CDS     42      650     .       -       0       ID=cds-pgaptmp_000001;Parent=gene-pgaptmp_000001;Name=extdb:pgaptmp_000001;Ontology_term=GO:0042953,GO:0042597;gbkey=CDS;gene=lolA;go_component=periplasmic space|0042597||IEA;g

Any help is much appreciated!

**Comment by JeanMainguy** [comment]
Hello,
There is probably something unexpected in your GFF files that PPanGGOLiN is not handling correctly. 
If it is not sensitive data, could you share the GFF file 80869.gff with us?

**Comment by whottel** [comment]
Hello, I am getting a similar issue when running files generated by PGAP. PGAP generates .gff,  fasta.gff, and .combined_fna_gff3.gff files. When trying all of these file types I get the same "Contig 1 already in genome" error. I was able to run PPanGGOLiN successfully with files generated by other genome annotators Bakta and Pirate.
Please find attached an example PGAP output file that I am trying to use (Compressed for the purposes of attaching here).

[2022CK-00463.combined_fna_gff3.zip](https://github.com/user-attachments/files/20462531/2022CK-00463.combined_fna_gff3.zip)

Please advise.

Thanks,
Wes

**Comment by whottel** [comment]
Great, thanks for the explanation!
