### ISSUE TITLE
Request: provide line number when cluster file input errors.

### ISSUE THREAD

**Issue by fwhelan** [labgem/PPanGGOLiN#30]
Hello again,

I am running into an error when I try to provide my own cluster file at the `ppanggolin cluster` step. Would it be possible for `ppanggolin` to output the line number in my input file that raises the error so that I can debug? When I was having issues with the annotate, the marker on the right  (# of organisms) really helped me narrow down my issue, but the number at the cluster step doesn't seem to match my number of genes.

Thank you!
--Fiona

```
$ ppanggolin cluster -p pangenome.h5 --clusters ppanggolin_clustersfile.tsv 
2020-04-08 16:14:49 main.py:l166 INFO   Command: /home/fwhelan/miniconda3/bin/ppanggolin cluster -p pangenome.h5 --clusters ppanggolin_clustersfile.tsv
2020-04-08 16:14:49 main.py:l167 INFO   PPanGGOLiN version: 1.1.83
2020-04-08 16:14:49 readBinaries.py:l37 INFO    Getting the current pangenome's status
2020-04-08 16:14:49 readBinaries.py:l283 INFO   Reading pangenome annotations...
100%| 1175179/1175179 [00:07<00:00, 165412.45gene/s]
100%| 209/209 [00:39<00:00,  5.31organism/s]
2020-04-08 16:15:37 cluster.py:l233 INFO        Reading ppanggolin_clustersfile.tsv the gene families file ...
 20%| 5514030/26997601 [00:06<00:13, 1545234.37bytes/s]
Traceback (most recent call last):
  File "/home/fwhelan/miniconda3/bin/ppanggolin", line 8, in <module>
    sys.exit(main())
  File "/home/fwhelan/miniconda3/lib/python3.7/site-packages/ppanggolin/main.py", line 171, in main
    ppanggolin.cluster.launch(args)
  File "/home/fwhelan/miniconda3/lib/python3.7/site-packages/ppanggolin/cluster/cluster.py", line 284, in launch
    readClustering(pangenome, args.clusters, args.infer_singletons, args.force)
  File "/home/fwhelan/miniconda3/lib/python3.7/site-packages/ppanggolin/cluster/cluster.py", line 247, in readClustering
    (fam_id, gene_id, is_frag) = elements if len(elements) == 3 else elements+[None]
ValueError: too many values to unpack (expected 3)
 21%| 5636655/26997601 [00:11<00:42, 501539.00bytes/s]
$ wc -l ppanggolin_clustersfile.tsv 
1161210 ppanggolin_clustersfile.tsv
```

**Comment by axbazin** [comment]
Yes I can add that.

Indeed, the progress bar is in bytes rather than in number of lines, as counting the number of lines requires to read the file (which becomes a bit redundant).

**Comment by axbazin** [comment]
latest commit (6c6257c) should be helpful for debugging your file

**Comment by fwhelan** [comment]
Thank you!!
