### ISSUE TITLE
Error RGP - Two regions had an identical name

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#34]
### version PPanGGOLiN

```
ppanggolin 1.1.85
```

###  PPanGGOLiN rgp command

```
ppanggolin rgp -p pangenome.h5
```

### Log

```
2020-05-28 00:12:32 main.py:l166 INFO	Command: /usr/local/bin/ppanggolin rgp -p pangenome.h5
2020-05-28 00:12:32 main.py:l167 INFO	PPanGGOLiN version: 1.1.85
2020-05-28 00:12:32 readBinaries.py:l37 INFO	Getting the current pangenome's status
2020-05-28 00:12:32 readBinaries.py:l283 INFO	Reading pangenome annotations...
100%|████████████████████████████████████████████████████████| 34334/34334 [00:00<00:00, 116881.11gene/s]
100%|████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  8.24organism/s]
2020-05-28 00:12:34 readBinaries.py:l289 INFO	Reading pangenome gene families...
100%|█████████████████████████████████████████████████████████| 33572/33572 [00:00<00:00, 75337.28gene/s]
100%|████████████████████████████████████████████████████| 3797/3797 [00:00<00:00, 83620.05gene family/s]
2020-05-28 00:12:34 genomicIsland.py:l183 INFO	Detecting multigenic families...
2020-05-28 00:12:34 pangenome.py:l296 INFO	30 gene families are defined as being multigenic. (duplicated in more than 0.05 of the genomes)
2020-05-28 00:12:34 genomicIsland.py:l185 INFO	Compute Regions of Genomic Plasticity ...
 44%|████████████████████████████▉                                    | 4/9 [00:00<00:00, 64.99genomes/s]
Traceback (most recent call last):
  File "/usr/local/bin/ppanggolin", line 11, in <module>
    load_entry_point('ppanggolin==1.1.85', 'console_scripts', 'ppanggolin')()
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.85-py3.6-linux-x86_64.egg/ppanggolin/main.py", line 189, in main
    ppanggolin.RGP.genomicIsland.launch(args)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.85-py3.6-linux-x86_64.egg/ppanggolin/RGP/genomicIsland.py", line 203, in launch
    predictRGP(pangenome, force = args.force, persistent_penalty=args.persistent_penalty, variable_gain=args.variable_gain, min_length=args.min_length, min_score=args.min_score, dup_margin=args.dup_margin, cpu=args.cpu)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.85-py3.6-linux-x86_64.egg/ppanggolin/RGP/genomicIsland.py", line 188, in predictRGP
    pangenome.addRegions(compute_org_rgp(org, persistent_penalty, variable_gain, min_length, min_score, multigenics))
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.85-py3.6-linux-x86_64.egg/ppanggolin/pangenome.py", line 311, in addRegions
    raise Exception("Two regions had an identical name, which was unexpected.")
Exception: Two regions had an identical name, which was unexpected.

```

The gff used in the `workflow` are produced by Prokka

**Comment by axbazin** [comment]
Looking briefly at the code around those parts, I think this should be possible only if two contigs in two different gff have the same identifier. Is it the case?

I will try to reproduce the error later today.

**Comment by Nilad** [comment]
Indeed, i follow the same classification for my assemblies. The longest contig is `ctg_1`, the second longest is `ctg_2` ...etc

**Comment by axbazin** [comment]
Alright, I will see if I can do something to deal with identical contig ids across genomes

**Comment by axbazin** [comment]
The last commit on the master branch should let you proceed with your analysis. All I did was adding genome names to the region identifiers when identical contig ids are seen so that they are still unique.

It did not raise any error when I tested it on the dataset I managed to reproduce your error on, so that should be good.

**Comment by Nilad** [comment]
It's work !
