### ISSUE TITLE
Gff3 and gbk files will not work but fasta does 

### ISSUE THREAD

**Issue by ManveerSangha** [labgem/PPanGGOLiN#54]
Hi there, 

I am trying to do an analysis of 33 prochlorococcus and synechococcus genomes using ppangolin. However, I keep on getting an error when I run gff3 and gbk files. I am sure that my format of my input file is correct since it works with fasta sequences. There has to be an issue with the formatting of these gff3 and gbk files. For gff3 files, the files begin with "##gff-version 3" as the program requires. Also, for the gbk files, the files begin with the locus as the program requires. Also, I am running the command "ppanggolin workflow --anno" so it should work with gff3 and gbk files as stated on the website. So I am unsure why ppangolin keeps on producing an error. Here is the error message I keep on receiving: 
-----start
2021-02-06 16:16:33 main.py:l169 INFO	Command: /usr/local/source/miniconda3/bin/ppanggolin workflow --anno test_input
2021-02-06 16:16:33 main.py:l170 INFO	PPanGGOLiN version: 1.1.96
2021-02-06 16:16:33 annotate.py:l322 INFO	Reading test_input the list of organism files ...
  0%|                                                                                                                                                                               | 0/2 [00:00<?, ?file/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/source/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/annotate/annotate.py", line 312, in launchReadAnno
    return readAnnoFile(*args)
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/annotate/annotate.py", line 317, in readAnnoFile
    return read_org_gff(organism_name, filename, circular_contigs, getSeq, pseudo)
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/annotate/annotate.py", line 243, in read_org_gff
    attributes = getGffAttributes(gff_fields)
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/annotate/annotate.py", line 197, in getGffAttributes
    attributes_field = [f for f in gff_fields[GFF_attribute].strip().split(';') if len(f)>0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/source/miniconda3/bin/ppanggolin", line 10, in <module>
    sys.exit(main())
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/main.py", line 180, in main
    ppanggolin.workflow.workflow.launch(args)
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/workflow/workflow.py", line 29, in launch
    readAnnotations(pangenome, args.anno, cpu = args.cpu, getSeq = getSeq)
  File "/usr/local/source/miniconda3/lib/python3.6/site-packages/ppanggolin/annotate/annotate.py", line 334, in readAnnotations
    for org, flag in p.imap_unordered(launchReadAnno, args):
  File "/usr/local/source/miniconda3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
IndexError: list index out of range
  0%|          
-------- end       
              
I would really appreciate it if you could help me troubleshoot this problem. Thank you for your time in advance. 

Sincerely,
Manveer

**Comment by axbazin** [comment]
Hi,

It looks like the program does not find as many field as it should when reading one of the lines of the first gff. Could you the first gff of your list to me so I can check what is wrong? You can attach a file to the issue to share one easily.

Adelme

**Comment by axbazin** [comment]
Actually looking at the log, it seems that the input file 'test_input' may have a problem. It looks like it only has two lines where you would expect to have 33 (one line per genome). If having a pangenome of two genomes was not something voluntary, your problem might be there. You can add your 'test_input' file to the issue so I can check if there is something wrong with it, if you want.

**Comment by ManveerSangha** [comment]
Hi there,

So the reason my input file has only 2 is because I was testing it with just 2 genomes. I have attached a link to the gff file of both the genomes I was testing it with and the input file as well. 
https://www.dropbox.com/sh/2bv79jbhemrobje/AAA9R6gmkPBglhu1qnftcn1Xa?dl=0

**Comment by axbazin** [comment]
Hi,

An empty line at the end of the files made it raise an error. Removing the empty line was enough to not raise this error anymore.  I'll modify the code slightly to cope with empty lines in the files, and see if I can improve the log of this part of the code.

Beware however that, since your gff do not have fasta sequences, you'll have to provide either the fasta sequences (through the --fasta option) or the clusters directly (through the --clusters option), as PPanGGOLiN needs either the fasta sequences to do the clustering, or the result of a clustering to partition the pangenome.

Good luck for your analysis, if you run into additional troubles or if you have questions please do not hesitate to raise another issue !

Adelme

**Comment by ManveerSangha** [comment]
Thank you so much for your help! The empty lines were the issue, even for gbk files. Runs fine now. If there are any other problems, I will definitely raise an issue. 

Sincerely,
Manveer
