### ISSUE TITLE
Problem of file format with Bakta

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#66]
I test PPanGGOLiN with [Bakta](https://github.com/oschwengers/bakta) outputs.

With .gbff ==> .gbk, it's working as wanted. +1
But with .gff3 ==> .gff, it seems have a format problem. =(

```
singularity exec --no-home --cleanenv -B /myhome:/myhome ~/Bureau/Tools/PPanGGOLin/PPanGGOLin.simg ppanggolin workflow --anno organism_list.tsv --output ppanggolin_dir
2021-09-27 10:23:56 main.py:l180 INFO	Command: /usr/local/bin/ppanggolin workflow --anno organism_list.tsv --output ppanggolin_dir
2021-09-27 10:23:56 main.py:l181 INFO	PPanGGOLiN version: 1.1.159
2021-09-27 10:23:56 annotate.py:l340 INFO	Reading organism_list.tsv the list of organism files ...
  0%|                                                                          | 0/183 [00:00<?, ?file/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 328, in readAnnoFile
    return read_org_gff(organism_name, filename, circular_contigs, getSeq, pseudo)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 253, in read_org_gff
    attributes = getGffAttributes(gff_fields)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 204, in getGffAttributes
    attributes_field = [f for f in gff_fields[GFF_attribute].strip().split(';') if len(f)>0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 322, in launchReadAnno
    return readAnnoFile(*args)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 330, in readAnnoFile
    raise Exception(f"Reading the gff3 file '{filename}' raised an error.")
Exception: Reading the gff3 file '/myhome/Bureau/test/all_gff/174C3.gff3' raised an error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ppanggolin", line 33, in <module>
    sys.exit(load_entry_point('ppanggolin==1.1.159', 'console_scripts', 'ppanggolin')())
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/main.py", line 191, in main
    ppanggolin.workflow.workflow.launch(args)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/workflow/workflow.py", line 29, in launch
    readAnnotations(pangenome, args.anno, cpu = args.cpu, getSeq = getSeq, show_bar=args.show_prog_bars)
  File "/usr/local/lib/python3.6/dist-packages/ppanggolin-1.1.159-py3.6-linux-x86_64.egg/ppanggolin/annotate/annotate.py", line 351, in readAnnotations
    for org, flag in p.imap_unordered(launchReadAnno, args):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
Exception: Reading the gff3 file '/myhome/Bureau/test/all_gff/174C3.gff3' raised an error.
  0%|                                                                          | 0/183 [00:00<?, ?file/s]
``` 

1 - Can be possible to have a check format with clear error message (like 'format is not correct.') ? 
2 - Can be possible to take in input the .gff3 of bakta ? 

Thanks in advance.

**Comment by axbazin** [comment]
Hi,

That bug was fixed with commit 5a6c21c, if you update your version of ppanggolin it should work fine.

The current message is "Exception: Reading the gff3 file '/myhome/Bureau/test/all_gff/174C3.gff3' raised an error."
I'd rather have this slightly more generic message than "format is not correct" for those cases, as here the bakta format is correct, it is the parser that was wrongly made.

Adelme
