### ISSUE TITLE
drawing some spot is not working ValueError

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#97]
Hello,

I'm trying to have the interactive spot plot for some specific spot so I've try the following command:

```bash
ppanggolin draw -p pangenome.h5 --spots spot_117
```

But I've got the following log:
```bash
2022-10-27 04:11:15 main.py:l214 INFO   Command: /grid/sw/ppanggolin/1.2.74/bin/ppanggolin draw -p pangenome.h5 --spots spot_117
2022-10-27 04:11:15 main.py:l215 INFO   PPanGGOLiN version: 1.2.74
2022-10-27 04:11:15 readBinaries.py:l39 INFO    Getting the current pangenome's status
2022-10-27 04:11:15 readBinaries.py:l389 INFO   Reading pangenome annotations...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 317841/317841 [00:02<00:00, 150322.64gene/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:07<00:00,  5.88organism/s]
2022-10-27 04:11:25 readBinaries.py:l403 INFO   Reading pangenome gene families...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313360/313360 [00:03<00:00, 104010.35gene/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26667/26667 [00:00<00:00, 28093.75gene family/s]
2022-10-27 04:11:29 readBinaries.py:l418 INFO   Reading the RGP...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 81783/81783 [00:00<00:00, 168869.92gene/s]
2022-10-27 04:11:30 readBinaries.py:l425 INFO   Reading the spots...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1572/1572 [00:00<00:00, 26473.32region/s]
2022-10-27 04:11:30 readBinaries.py:l432 INFO   Reading the modules...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6292/6292 [00:00<00:00, 157853.39module/s]
2022-10-27 04:11:30 draw_spot.py:l530 INFO      Drawing the following spots: spot_117
2022-10-27 04:11:30 draw_spot.py:l448 INFO      Ordering genes among regions, and drawing spots...
  0%|                                                                                                                                                                               | 0/1 [00:00<?, ?spot/s]
Traceback (most recent call last):
  File "/grid/sw/ppanggolin/1.2.74/bin/ppanggolin", line 11, in <module>
    load_entry_point('ppanggolin==1.2.74', 'console_scripts', 'ppanggolin')()
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/main.py", line 229, in main
    ppanggolin.figures.launch(args)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/figures/drawing.py", line 26, in launch
    drawSpots(pangenome=pangenome, output=args.output, spot_list=args.spots, disable_bar=args.disable_prog_bar)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/figures/draw_spot.py", line 535, in drawSpots
    drawSelectedSpots(selected_spots, pangenome, output,
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/figures/draw_spot.py", line 492, in drawSelectedSpots
    GeneLists = orderGeneLists(GeneLists, overlapping_match, exact_match, set_size)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/figures/draw_spot.py", line 50, in orderGeneLists
    return rowOrderGeneLists(geneLists)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/figures/draw_spot.py", line 70, in rowOrderGeneLists
    hc = linkage(dist, 'single')
  File "/grid/sw/python/3.8.5/lib/python3.8/site-packages/scipy/cluster/hierarchy.py", line 1068, in linkage
    n = int(distance.num_obs_y(y))
  File "/grid/sw/python/3.8.5/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2555, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

I've try this for 3 different spot I would like to investigate more, but got the same error for all.
Any idea how to solve this?

Thanks in advance
Have a great day
C.

**Comment by axbazin** [comment]
Hi,

Is there a chance that in the 'summarize_spots.tsv' file, the number of RGP or the nb_unique_family_sets for those spots is 1 ?

Adelme

**Comment by cmonat** [comment]
Hello,

yes for all of them both the number of RGP and the number of unique family set is 1.
C.

**Comment by axbazin** [comment]
aha I see where the problem is then. Those regions only have a single kind of gene ordering, and to order the regions in the figure we use single linkage clustering + a dendrogram function that computes the ordering based on the difference between gene organizations in RGPs of the same spot. It seems that they don't accept inputs with no differences.

I'll try to fix this in the master branch so that spots with only one RGP (or equivalently one kind of gene organization) can be drawn as well, I'll tell you when it's done.

Adelme

**Comment by axbazin** [comment]
Hi, 

I actually managed to replicate the issue with the testing dataset. The latest commit on the master branch of the repository fixed it for me.

If I remember correctly you are in an atypical environment. There has been a few changes since 1.2.74, but no new dependency, so normally everything should work fine by just updating ppanggolin itself. Will you be able to install ppanggolin from the github repository ?

Adelme

**Comment by cmonat** [comment]
Hi,

thanks a lot.
I have to ask the IT team to do it, I'll let you know if this works for me.

C.

**Comment by cmonat** [comment]
Hello,

I've tried to rerun the draw spot after loading the new version (1.2.96) and I got this meesage:

```bash
ppanggolin draw -p pangenome.h5 --spots spot_182
2022-11-03 05:15:47 utils.py:l87 INFO   Command: /grid/sw/ppanggolin/1.2.96/bin/ppanggolin draw -p pangenome.h5 --spots spot_182
2022-11-03 05:15:47 utils.py:l88 INFO   PPanGGOLiN version: 1.2.96
2022-11-03 05:15:47 readBinaries.py:l39 INFO    Getting the current pangenome status
Traceback (most recent call last):
  File "/grid/sw/ppanggolin/1.2.96/bin/ppanggolin", line 11, in <module>
    load_entry_point('ppanggolin==1.2.96', 'console_scripts', 'ppanggolin')()
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/main.py", line 159, in main
    ppanggolin.figures.launch(args)
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/figures/drawing.py", line 20, in launch
    pangenome.add_file(args.pangenome)
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/pangenome.py", line 63, in add_file
    get_status(self, pangenome_file)
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/formats/readBinaries.py", line 55, in get_status
    status_group._v_attrs.Partitioned = True
  File "/grid/sw/python/3.8.5/lib/python3.8/site-packages/tables/attributeset.py", line 461, in __setattr__
    nodefile._check_writable()
  File "/grid/sw/python/3.8.5/lib/python3.8/site-packages/tables/file.py", line 2112, in _check_writable
    raise FileModeError("the file is not writable")
tables.exceptions.FileModeError: the file is not writable
Closing remaining open files:pangenome.h5...done
```

Maybe I should rerun the pangenome creation with the new version?
Thanks for your help

have a great day
C.

**Comment by axbazin** [comment]
Hi,

Ah yes, sorry for this. If you can indeed rerun the pangenome creation with this new version, it will solve it.

Adelme

**Comment by cmonat** [comment]
Perfectly working!
Thanks a lot

C.

**Comment by axbazin** [comment]
Awesome !
Thank you for reporting this issue !

Adelme
